# This file is part of gepd.
# https://github.com/lichtbaer/dawum

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2018, johannes <johannes@kampagnen.eu>

language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
